name: Initial Frontend Pipeline

on:
  push:
    paths:
      - frontend/**
  pull_request:
    branches:
      - main
      - development
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    environment: frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (frontend)
        run: |
          npm install

      - name: Build frontend
        env:
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          npm run build
